stages:
  fetch:
    cmd: |
      poetry run python src/data/fetch_air_data.py
      git commit -am "Updated raw air data on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
    - src/data/fetch_air_data.py
    params:
    - fetch.url
    outs:
    - data/raw/air/air_data.xml
    always_changed: true

  preprocess:
    cmd: |
      poetry run python src/data/preprocess_air_data.py
      git commit -am "Updated preprocessed air data on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
    - src/data/preprocess_air_data.py
    - data/raw/air/air_data.xml
    outs:
    - data/preprocessed/air:
        persist: true