stages:
  fetch:
    cmd: poetry run python src/data/fetch_air_data.py
    deps:
    - src/data/fetch_air_data.py
    params:
    - fetch.url
    outs:
    - data/raw/air/air_data.xml
    always_changed: true

  preprocess:
    cmd: poetry run python src/data/preprocess_air_data.py
    deps:
    - src/data/preprocess_air_data.py
    - data/raw/air/air_data.xml
    outs:
    - data/preprocessed/air:
        persist: true

  validate:
    cmd: |
      cd gx && poetry run python run_checkpoint.py
    deps:
    - data/preprocessed/air/
    outs:
    - gx/uncommitted/data_docs/local_site:
        persist: true