name: Fetch data on schedule

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_air:
    name: Fetch and pre-process air data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Install Poetry
        run: |
          pipx install poetry
  
      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry
      
      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
        
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: DVC setup remote
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}

      - name: Run DVC pipeline
        env:
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY }}
        run: |
          dvc pull
          dvc status
          dvc repro
          dvc push
          git add dvc.lock
          git commit -m "Update dvc.lock on `date` with GitHub Actions" || true

      - name: Deploy DataDocs to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "reports"
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}